language: ruby

rvm:
  - 2.1
  - 2.2
  - 2.3

sudo: false
cache: bundler

before_install: gem install bundler -v 1.11.2
bundler_args: --without development --retry=3 --jobs=3

script:
  - bundle exec rake

env:
  # global:
  #   - TRELLO_APP_KEY='tacokit-app-key'

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
