language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head

sudo: false
cache: bundler

bundler_args: --without development --retry=3 --jobs=3

script:
  - bundle exec rake

env:
  # global:
  #   - TRELLO_APP_KEY='tacokit-app-key'

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
